# SPDX-License-Identifier: MIT
# Copyright (C) 2022 iris-GmbH infrared & intelligent sensors

FROM mikefarah/yq:4.45.4 AS yq

FROM ghcr.io/siemens/kas/kas:4.8
LABEL maintainer="Jasper Orschulko <Jasper.Orschulko@iris-sensing.com>"
USER root
# renovate: datasource=repology depName=debian_12/awscli
ARG AWSCLI_VERSION="2.9.19-1"
# renovate: datasource=repology depName=debian_12/ca-certificates
ARG CA_CERTIFICATES_VERSION="20230311"
# renovate: datasource=repology depName=debian_12/cmake
ARG CMAKE_VERSION="3.25.1-1"
# renovate: datasource=repology depName=debian_12/jq
ARG JQ_VERSION="1.6-2.1"
# renovate: datasource=repology depName=debian_12/python3-pip
ARG PYTHON3_PIP_VERSION="23.0.1+dfsg-1"
# renovate: datasource=repology depName=debian_12/python3-click
ARG PYTHON3_CLICK_VERSION="8.1.3-2"
# renovate: datasource=repology depName=debian_12/python3-requests
ARG PYTHON3_REQUESTS_VERSION="2.28.1+dfsg-1"
# renovate: datasource=repology depName=debian_12/python3-gitlab
ARG PYTHON3_GITLAB_VERSION="1:3.12.0-1"
# renovate: datasource=repology depName=debian_12/skopeo
ARG SKOPEO_VERSION="1.9.3+ds1-1+b9"
RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        awscli=${AWSCLI_VERSION} \
        ca-certificates=${CA_CERTIFICATES_VERSION} \
        cmake=${CMAKE_VERSION} \
        jq=${JQ_VERSION} \
        python3-pip=${PYTHON3_PIP_VERSION} \
        python3-click=${PYTHON3_CLICK_VERSION} \
        python3-requests=${PYTHON3_REQUESTS_VERSION} \
        python3-gitlab=${PYTHON3_GITLAB_VERSION} \
        skopeo=${SKOPEO_VERSION} \
    && rm -rf /var/lib/apt/lists
COPY --from=yq /usr/bin/yq /usr/bin/yq
ADD utils/create_gitlab_release/src/create_gitlab_release.py /usr/bin/create_gitlab_release
USER builder
RUN yq --version
RUN create_gitlab_release --help
