# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: '3'

services:
  kas:
    build:
      dockerfile: Dockerfile.qemu
      context: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    working_dir: /mnt/yocto-kas
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/mnt/yocto-kas
      - ${SSH_DIR:-~/.ssh}:/etc/skel/.ssh
