FROM python:3.11.4-bullseye as build
ARG SDK_SOURCE
ADD ${SDK_SOURCE} /${SDK_SOURCE}
RUN SCRIPT=$(find /${SDK_SOURCE} -type f -name "*.sh") \
    && if test -z "${SCRIPT}"; then echo "No sh script found in ${SDK_SOURCE}"; fi \
    && /bin/sh ${SCRIPT} -d /sdk -y

FROM debian:bullseye-slim
COPY --from=build /sdk /sdk
ADD entrypoint_sdk.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
