# SPDX-License-Identifier: MIT
# Copyright (C) 2022 iris-GmbH infrared & intelligent sensors

FROM mikefarah/yq:4.33.2 AS yq

FROM ghcr.io/siemens/kas/kas:4.1
LABEL maintainer="Jasper Orschulko <Jasper.Orschulko@iris-sensing.com>"
USER root
RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        awscli \
        ca-certificates \
        cmake \
        jq \
        python3-pip \
        python3-click \
        python3-requests \
        python3-gitlab \
    && rm -rf /var/lib/apt/lists
COPY --from=yq /usr/bin/yq /usr/bin/yq
ADD utils/create_gitlab_release/src/create_gitlab_release.py /usr/bin/create_gitlab_release
USER builder
RUN yq --version
RUN create_gitlab_release --help
