# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: '3'

services:
  kas:
    build:
      dockerfile: Dockerfile_iris_kas
      context: .
    working_dir: /mnt/yocto-kas
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/mnt/yocto-kas:z
      - ${SSH_DIR:-~/.ssh}:/etc/skel/.ssh
      # Replace $GITFILE (or .gitignore) with /dev/null in docker (the file remains untouched outside the container!)
      - /dev/null:/mnt/yocto-kas/${GITFILE:-/.gitignore}
    ports:
      # expose QEMU SSH port to host
      - "127.0.0.1:2222:2222"
