version: '3'

services:
  kas:
    image: ghcr.io/siemens/kas/kas:2.4
    working_dir: /mnt/yocto-kas
    environment:
      - USER_ID
      - KAS_WORK_DIR=/mnt/yocto-kas
      - KAS_BUILD_DIR=$${KAS_WORK_DIR}/build
    volumes:
      - ./:/mnt/yocto-kas
      - ~/.ssh:/builder/.ssh
