# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # make sure ownership of mounted EFS volumes is correct
      - sudo chown builder:builder /mnt/yocto_cache/dl_dir /mnt/yocto_cache/sstate_cache
      # set target images
      - export images="$(for i in ${IMAGES}; do echo -n "mc:${MULTI_CONF}:${i} "; done)"
      # clone layer repos and try to checkout the current branch name in all meta layers
      # populate sstate on builds of iris-kas develop branches
      - "if [ \"${JOB_NAME}\" = \"iris-kas-develop\" ] && [ \"$(basename ${GIT_BRANCH})\" = \"develop\" ]; then echo \"Info: Populating caches...\" && export POPULATE_CACHES=\":include/kas-irma6-jenkins-populate-caches.yml\"; fi"
      - kas for-all-repos --update kas-irma6-pa.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES} "git checkout ${GIT_BRANCH} 2> /dev/null || true"

  build:
    on-failure: ABORT
    commands:
      # build artifacts
      - kas shell -k -c "bitbake ${images}" kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}
      - kas shell -k -c "bitbake mc:${MULTI_CONF}:${SDK_IMAGE} -c populate_sdk" kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}
