# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # make sure ownership of mounted EFS volumes is correct
      - sudo chown builder:builder /mnt/yocto_cache/dl_dir /mnt/yocto_cache/sstate_cache /mnt/yocto_cache/sstate_release_cache
      # make sure sstate release cache is empty
      - "[ $(find /mnt/yocto_cache/sstate_release_cache -mindepth 1 | wc -l) -eq 0 ] || { echo \"Error: sstate release cache is not clean.\"; exit 1; }"
      - "echo Info: Making sure fixed refspecs are set..."
      - "kas for-all-repos kas-irma6-base.yml 'if [ \"${KAS_REPO_NAME}\" != \"this\" ]; then git rev-parse --abbrev-ref HEAD | grep -qE \"^HEAD\\s*$\" || { echo \"Error: Non-fixed refspec detected in repo ${KAS_REPO_NAME}. Please set to a git commit hash or tag for a release build\"; exit 1; }; fi'"
      - "echo Info: Fetching base sources..."
      - kas shell --update -c "bitbake mc:${MULTI_CONF}:irma6-base --runonly=fetch" kas-irma6-base.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-release-fetch.yml
      # replace softlinks with copies for packaging purposes
      - for f in $(find build/dl_dir -type l); do cp --remove-destination $(readlink $f) $f; done;
      # create a tar archive containing the complete build environment while preserving file permissions
      - touch ${MULTI_CONF}-base-sources.tar
      - tar --exclude=${MULTI_CONF}-base-sources.tar --exclude=build/tmp --exclude=build/dl_dir/git2 -cf ${MULTI_CONF}-base-sources.tar .

  build:
    on-failure: ABORT
    commands:
      - "echo Info: Attempting to build the base image offline..."
      - kas shell -c "bitbake mc:${MULTI_CONF}:irma6-base" kas-irma6-base.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-release.yml:include/kas-offline-build.yml

artifacts:
  files:
    - "${MULTI_CONF}-base-sources.tar"
