# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # make sure ownership of mounted EFS volume is correct
      - sudo chown builder:builder /mnt/yocto_cache

  build:
    on-failure: ABORT
    commands:
      # fetch sources for all multi_confs and images
      - "export targets=\"$(for i in ${TARGETS}; do echo -n \"mc:${i} \"; done)\""
      - echo "$targets"
      - kas shell --update -c "bitbake ${targets} --runonly=fetch" kas-irma6-pa.yml:include/kas-irma6-jenkins-release-fetch.yml
      # rsync dl-dir to pre-mirror location for future use, exclude "done" files, redundant git2folder and softlinks to mirror location
      - sudo rsync -avh --exclude=*.done --exclude=git2 --no-links build/dl_dir/ /mnt/yocto_cache/dl_dir/
