# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors

version: 0.2

run-as: root

phases:
  build:
    on-failure: ABORT
    commands:
      # ensure release sstate cache is wiped in preparation of release build
      - find /mnt/yocto_cache/sstate_release_cache/ -mindepth 1 -delete
