# SPDX-License-Identifier: MIT
# Copyright (C) 2021 iris-GmbH infrared & intelligent sensors
#
#
# Modifications to the bblayers.conf and local.conf file

header:
  version: 9

env:
  # define BB_ENV_PASSTHROUGH_ADDITIONS
  KAS_WORK_DIR: None

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""
    ACCEPT_FSL_EULA = "1"

local_conf_header:
  standard: |
    CONF_VERSION = "2"

  dl_dir: |
    DL_DIR ?= "${TOPDIR}/dl_dir"
  sstate_dir: |
    SSTATE_DIR ?= "${TOPDIR}/sstate_dir"


  diskmon: |
    BB_DISKMON_DIRS = "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"
